version: 2
updates:
  # Python dependencies - etos_lib
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      etos-lib:
        patterns:
          - "etos_lib"

  # Python dependencies - opentelemetry
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      opentelemetry:
        patterns:
          - "opentelemetry-*"
